---
new_page_extension: md
auto_deploy: false
admin_path: "/static/admin"
webhook_url: 
sections:
- type: document
  path: src/pages/index.md
  label: Home
- type: document
  path: src/pages/about/index.md
  label: About college
- type: document
  path: src/pages/about-trust/index.md
  label: About Trust
- type: document
  path: src/pages/words-from-chairman/index.md
  label: Words From Chairman
  match: "**/*"
- type: document
  path: src/pages/words-from-vice-chairman/index.md
  label: Words From Vice Chairman
  match: "**/*"
- type: document
  path: src/pages/words-from-director/index.md
  label: Words From Director
  match: "**/*"
- type: document
  path: src/pages/contact/index.md
  label: Contact Us
- type: directory
  path: src/pages/blog
  label: Blog Posts
  create: documents
  match: "**/*"
  exclude: index.js
  new_doc_ext: md
  templates:
  - blog-post
- type: directory
  path: src/pages/course
  label: Courses
  create: documents
  match: "**/*"
  exclude: index.js
  new_doc_ext: md
  templates:
  - course
- type: document
  path: src/pages/products/index.md
  label: Products
upload_dir: static/img
public_path: "/static/img"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv/public"
  instant_preview_command: npm run forestry-preview
